// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: schema.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Passenger int32

const (
	Passenger_UNKNOWN_PASSENGER Passenger = 0
	Passenger_ADULT             Passenger = 1
	Passenger_CHILD             Passenger = 2
	Passenger_INFANT_ON_LAP     Passenger = 3
	Passenger_INFANT_IN_SEAT    Passenger = 4
)

// Enum value maps for Passenger.
var (
	Passenger_name = map[int32]string{
		0: "UNKNOWN_PASSENGER",
		1: "ADULT",
		2: "CHILD",
		3: "INFANT_ON_LAP",
		4: "INFANT_IN_SEAT",
	}
	Passenger_value = map[string]int32{
		"UNKNOWN_PASSENGER": 0,
		"ADULT":             1,
		"CHILD":             2,
		"INFANT_ON_LAP":     3,
		"INFANT_IN_SEAT":    4,
	}
)

func (x Passenger) Enum() *Passenger {
	p := new(Passenger)
	*p = x
	return p
}

func (x Passenger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Passenger) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (Passenger) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x Passenger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Passenger.Descriptor instead.
func (Passenger) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	Class_UNKNOWN_CLASS   Class = 0
	Class_ECONOMY         Class = 1
	Class_PREMIUM_ECONOMY Class = 2
	Class_BUSINESS        Class = 3
	Class_FIRST           Class = 4
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "UNKNOWN_CLASS",
		1: "ECONOMY",
		2: "PREMIUM_ECONOMY",
		3: "BUSINESS",
		4: "FIRST",
	}
	Class_value = map[string]int32{
		"UNKNOWN_CLASS":   0,
		"ECONOMY":         1,
		"PREMIUM_ECONOMY": 2,
		"BUSINESS":        3,
		"FIRST":           4,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

type Trip int32

const (
	Trip_UNKNOWN_TRIP Trip = 0
	Trip_ROUND_TRIP   Trip = 1
	Trip_ONE_WAY      Trip = 2
)

// Enum value maps for Trip.
var (
	Trip_name = map[int32]string{
		0: "UNKNOWN_TRIP",
		1: "ROUND_TRIP",
		2: "ONE_WAY",
	}
	Trip_value = map[string]int32{
		"UNKNOWN_TRIP": 0,
		"ROUND_TRIP":   1,
		"ONE_WAY":      2,
	}
)

func (x Trip) Enum() *Trip {
	p := new(Trip)
	*p = x
	return p
}

func (x Trip) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Trip) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[2].Descriptor()
}

func (Trip) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[2]
}

func (x Trip) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Trip.Descriptor instead.
func (Trip) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

type Airport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Airport) Reset() {
	*x = Airport{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Airport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airport) ProtoMessage() {}

func (x *Airport) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airport.ProtoReflect.Descriptor instead.
func (*Airport) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Airport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Flight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	MaxStops      *int32                 `protobuf:"varint,5,opt,name=maxStops,proto3,oneof" json:"maxStops,omitempty"`
	Airlines      []string               `protobuf:"bytes,6,rep,name=airlines,proto3" json:"airlines,omitempty"`
	FromAirport   *Airport               `protobuf:"bytes,13,opt,name=fromAirport,proto3" json:"fromAirport,omitempty"`
	ToAirport     *Airport               `protobuf:"bytes,14,opt,name=toAirport,proto3" json:"toAirport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Flight) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Flight) GetMaxStops() int32 {
	if x != nil && x.MaxStops != nil {
		return *x.MaxStops
	}
	return 0
}

func (x *Flight) GetAirlines() []string {
	if x != nil {
		return x.Airlines
	}
	return nil
}

func (x *Flight) GetFromAirport() *Airport {
	if x != nil {
		return x.FromAirport
	}
	return nil
}

func (x *Flight) GetToAirport() *Airport {
	if x != nil {
		return x.ToAirport
	}
	return nil
}

type FlightPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Flight              `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Passengers    []Passenger            `protobuf:"varint,8,rep,packed,name=passengers,proto3,enum=internal.Passenger" json:"passengers,omitempty"`
	Class         Class                  `protobuf:"varint,9,opt,name=class,proto3,enum=internal.Class" json:"class,omitempty"`
	Trip          Trip                   `protobuf:"varint,19,opt,name=trip,proto3,enum=internal.Trip" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightPayload) Reset() {
	*x = FlightPayload{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightPayload) ProtoMessage() {}

func (x *FlightPayload) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightPayload.ProtoReflect.Descriptor instead.
func (*FlightPayload) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *FlightPayload) GetData() []*Flight {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FlightPayload) GetPassengers() []Passenger {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *FlightPayload) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNKNOWN_CLASS
}

func (x *FlightPayload) GetTrip() Trip {
	if x != nil {
		return x.Trip
	}
	return Trip_UNKNOWN_TRIP
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\binternal\"\x1d\n" +
	"\aAirport\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcc\x01\n" +
	"\x06Flight\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1f\n" +
	"\bmaxStops\x18\x05 \x01(\x05H\x00R\bmaxStops\x88\x01\x01\x12\x1a\n" +
	"\bairlines\x18\x06 \x03(\tR\bairlines\x123\n" +
	"\vfromAirport\x18\r \x01(\v2\x11.internal.AirportR\vfromAirport\x12/\n" +
	"\ttoAirport\x18\x0e \x01(\v2\x11.internal.AirportR\ttoAirportB\v\n" +
	"\t_maxStops\"\xb5\x01\n" +
	"\rFlightPayload\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.internal.FlightR\x04data\x123\n" +
	"\n" +
	"passengers\x18\b \x03(\x0e2\x13.internal.PassengerR\n" +
	"passengers\x12%\n" +
	"\x05class\x18\t \x01(\x0e2\x0f.internal.ClassR\x05class\x12\"\n" +
	"\x04trip\x18\x13 \x01(\x0e2\x0e.internal.TripR\x04trip*_\n" +
	"\tPassenger\x12\x15\n" +
	"\x11UNKNOWN_PASSENGER\x10\x00\x12\t\n" +
	"\x05ADULT\x10\x01\x12\t\n" +
	"\x05CHILD\x10\x02\x12\x11\n" +
	"\rINFANT_ON_LAP\x10\x03\x12\x12\n" +
	"\x0eINFANT_IN_SEAT\x10\x04*U\n" +
	"\x05Class\x12\x11\n" +
	"\rUNKNOWN_CLASS\x10\x00\x12\v\n" +
	"\aECONOMY\x10\x01\x12\x13\n" +
	"\x0fPREMIUM_ECONOMY\x10\x02\x12\f\n" +
	"\bBUSINESS\x10\x03\x12\t\n" +
	"\x05FIRST\x10\x04*5\n" +
	"\x04Trip\x12\x10\n" +
	"\fUNKNOWN_TRIP\x10\x00\x12\x0e\n" +
	"\n" +
	"ROUND_TRIP\x10\x01\x12\v\n" +
	"\aONE_WAY\x10\x02B.Z,github.com/rodatboat/google-flights/internalb\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_proto_goTypes = []any{
	(Passenger)(0),        // 0: internal.Passenger
	(Class)(0),            // 1: internal.Class
	(Trip)(0),             // 2: internal.Trip
	(*Airport)(nil),       // 3: internal.Airport
	(*Flight)(nil),        // 4: internal.Flight
	(*FlightPayload)(nil), // 5: internal.FlightPayload
}
var file_schema_proto_depIdxs = []int32{
	3, // 0: internal.Flight.fromAirport:type_name -> internal.Airport
	3, // 1: internal.Flight.toAirport:type_name -> internal.Airport
	4, // 2: internal.FlightPayload.data:type_name -> internal.Flight
	0, // 3: internal.FlightPayload.passengers:type_name -> internal.Passenger
	1, // 4: internal.FlightPayload.class:type_name -> internal.Class
	2, // 5: internal.FlightPayload.trip:type_name -> internal.Trip
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	file_schema_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
